### ISSUE TITLE
Unable to add # to the dialed number

### ISSUE THREAD

**Issue by kamaroly** [Rohfosho/CordovaCallNumberPlugin#10]
HI, 
First of all, I would like to thank you for this wonderful plugin. 
It works well however I have a small issue, I want to dial a ussd, with below codes, it is dialing *500 not *500#
```javascript
     window.plugins.CallNumber.callNumber(function(results){
      console.log(results);
    }, function(onError){
      console.log(onError);
    }, '*500#');

**Comment by zweii** [comment]
# is a reserved character in an URI so you or the plugin have to encode it.

**Comment by nishilshah17** [comment]
Encoded it using "%23". Is the issue on iOS as well?
