### ISSUE TITLE
Does not bypass Skype

### ISSUE THREAD

**Issue by leouze** [Rohfosho/CordovaCallNumberPlugin#11]
When installed on the device with Skype, Skype intercepts any call protocol from app. Is this intended?

**Comment by nishilshah17** [comment]
No, it is not intended. It may be a setting on your phone to have all call protocols handled through the Skype application.

**Comment by leouze** [comment]
I mean it is not intercepted literally but when you are trying to execute the script and you have Skype installed, it shows you if you want to make the call using Skype or Phone (Normal/Native Call).

**Comment by nishilshah17** [comment]
Oh yes, that is intended. A few of the users wanted the option of making the calls through alternative applications. What's the issue with that being there? You can select whichever app you want and then select the checkbox saying "Always use this app".

**Comment by leouze** [comment]
I'm making an emergency/SOS app and having an action sheet for an immediate call does not meet the purpose of it being an emergency app?

**Comment by nishilshah17** [comment]
Is this urgent? I'll look into it sometime over the next few days and get it fixed.

**Comment by leouze** [comment]
If at least can be delivered within this month that will be great! I think it should be added as a feature where the developers can choose whether to show action sheet or just execute the call immediately.

**Comment by nishilshah17** [comment]
Committed the feature. Let me know if it does not work as you expected.

**Comment by leouze** [comment]
Hi Nishil,
Great I will try it this weekend thank you very much for immediate action.
I appreciate it!
All the best!

**Comment by nishilshah17** [comment]
Did you try the new feature?

**Comment by martyzz1** [comment]
I have skype installed on my android 5, and the new feature works for me perfectly fine. I haven't tested it on ios yet, but I will do early next week.   @leouze given this was a feature you asked for - your lack of feedback is :disappointed:
