### ISSUE TITLE
Call time

### ISSUE THREAD

**Issue by rafal-leap** [Rohfosho/CordovaCallNumberPlugin#12]
Hi does your plugin supports call time or callback based on call finished?

**Comment by nishilshah17** [comment]
Hello, we don't have support for that as of now. If you'd like to add it, submit a pull request.

**Comment by rafal-leap** [comment]
Hi I'm unable to create a pull request when there is only one branch to choose from...

"Choose different branches or forks above to discuss and review changes."

Could you please add:
call_completed: true/false
call_time: 02:05:12

or similar. I look forward for the feature...Thanks

**Comment by ShivBagherwal** [comment]
I also need to have this feature....can you please add this feature? This would be great.
