### ISSUE TITLE
Android permission to call

### ISSUE THREAD

**Issue by hackerunet** [Rohfosho/CordovaCallNumberPlugin#13]
Hello, I'm building a cordova application, I need to enable android permissions to allow make a phone call, please tell me what would be the xml structure to enable this, for example here is a list of xml params I need to send sms and enable geolocation:
```
<plugin name="SplashScreen" value="org.apache.cordova.SplashScreen"/>
    <feature name="SmsPlugin">
        <param name="android-package" value="org.apache.cordova.plugin.SmsPlugin"/>
    </feature>
    <feature name="geolocation">
       <param name="android-package" value="org.apache.cordova.geolocation"/>
    </feature>
```

**Comment by rafal-leap** [comment]
Based on this article: http://rickluna.com/wp/2012/02/making-a-phone-call-from-within-phonegap-in-android-and-ios/

<access origin="tel:*" launch-external="yes" />

Should do the job.
