### ISSUE TITLE
Possible Android 6 compatibility issue

### ISSUE THREAD

**Issue by markdagher** [Rohfosho/CordovaCallNumberPlugin#18]
Hello,

The plugin was working perfectly when I first used it (around 2 weeks ago), and then suddenly inexplicably started throwing "CannotCallNumberError" on my android testing device.

These are the project details:
Cordova version 6.0.0
Ionic 1.7.14
Call-number plugin : mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
number format (both iOS and Android): "+961*******" (I'm 100% sure the number is a valid one)
Android version: 6.0

The plugin is working flawlessly on iOS devices, so I'm inclined to think that it is an issue with Android 6.0.

Any help would be appreciated!

**Comment by jadsalhani** [comment]
+1, same issue I'm having
