### ISSUE TITLE
Android 6.0

### ISSUE THREAD

**Issue by rafaelddias** [Rohfosho/CordovaCallNumberPlugin#20]
When trying to place a call on Android 6.0, occurs an error with the following message : CouldNotCallPhoneNumber

**Comment by oorodong** [comment]
use this 
`function permisioncall(){
		cordova.plugins.diagnostic.requestRuntimePermission(function(status){
		    switch(status){
		        case cordova.plugins.diagnostic.permissionStatus.GRANTED:
		            console.log("Permission granted to use the camera");
		            $scope.Call();
		            break;
		        case cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED:
		            console.log("Permission to use the camera has not been requested yet");
		            break;
		        case cordova.plugins.diagnostic.permissionStatus.DENIED:
		            console.log("Permission denied to use the camera - ask again?");
		            break;
		        case cordova.plugins.diagnostic.permissionStatus.DENIED_ALWAYS:
		            console.log("Permission permanently denied to use the camera - guess we won't be using it then!");
		            break;
		    }
		}, function(error){
		    console.error("The following error occurred: "+error);
		}, cordova.plugins.diagnostic.runtimePermission.CALL_PHONE);
	}`

**Comment by paulb2011** [comment]
Any update on this issue? I'm seeing the same problem since upgrading Android to version 6.
