### ISSUE TITLE
Documentation not detailed

### ISSUE THREAD

**Issue by PrinceYoulou** [Rohfosho/CordovaCallNumberPlugin#22]
It would be great to have a full explained text on how to use this plugin and some example. I am new to this, so i want to understand how it works. thanks

**Comment by nishilshah17** [comment]
Please check out the README. I've updated it with an example on how to implement the `onSuccess` and `onError` functions. All the information you need is on the README. Install the plugin, then call the `callNumber` function as shown.

**Comment by PrinceYoulou** [comment]
Thanks! closed#22

**Comment by PrinceYoulou** [comment]
Closed#22
