### ISSUE TITLE
Phonegap 4 PGB

### ISSUE THREAD

**Issue by vespino** [Rohfosho/CordovaCallNumberPlugin#23]
When compiling for Phonegap 4.1.1 (Android/PGB) I get the following error:

 Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: CFCallNumber.java - You can fix this here 

Any chance of fixed this?

**Comment by brucco1980** [comment]
For starters, great plugin! I'm getting the same error as @vespino. 

I'm using Phonegap Build:
PhoneGap (iOS / Android / Windows)
cli-5.2.0 (3.9.1 / 4.1.1 / 3.8.1)

Are there any updates on this fix yet?
