### ISSUE TITLE
Uncaught TypeError: Cannot read property 'CallNumber' of undefined

### ISSUE THREAD

**Issue by swanandvaidya** [Rohfosho/CordovaCallNumberPlugin#24]
Error while calling this plugin i got error mentioned in title.
Please help me whats the problem is CallNumber.js is correct ??

**Comment by chiragandroid** [comment]
i have the same issue of Cannot read property 'CallNumber' of undefined

**Comment by CrackerakiUA** [comment]
I have same issue.
When i am doing cordova plugin list, among other plugins i see `mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"`.
When i am doing `console.log(window.plugins);` i don't see the plugin on android device, but when i am opening browser in pc i see it.

**Comment by Seongsoo-Kim** [comment]
When I try this plugin in phonegap desktop app + phonegap app, it doesn't work. but after phonegap build, it works perfectly.

**Comment by maximooo** [comment]
am having the same issue and it was working fine month ago .... can any one help me please i spent two day looking for solution ??? :(

**Comment by kumquat0601** [comment]
@maximooo  Do you check copying and pasting CallNumber.js into your www/ folder and importing into your index.html ???

**Comment by maximooo** [comment]
@kumquat0601 i did and still giving me same error anyone can help

**Comment by cozzbie** [comment]
If `window.plugins` is returning undefined, try `window.cordova.plugins`

**Comment by 606ep** [comment]
It looks like installing plugin with:
cordova plugin add https://github.com/Rohfosho/CordovaCallNumberPlugin.git 

fixes this issue

**Comment by pankaja92** [comment]
Today I added this plugin for my app. And I'm getting the error.

I added the plugin using **cordova plugin add https://github.com/Rohfosho/CordovaCallNumberPlugin.git**
and tried changing _window.plugins_ to _window.cordova.plugins_ too. 
But still no good.

**Comment by admiremasaga** [comment]
change this

window.plugins.CallNumber.callNumber(onSuccess, onError, number, bypassAppChooser);

to

window.plugins.CallNumber.callNumber(onSuccess, onError, number, false);


this worked for me by adding false instead of bypassAppChooser

**Comment by abdelibbi** [comment]
Hi everyone !!
did someone found a solution to this issue ??
thanks for your reaction.

**Comment by LimitlessDonald** [comment]
Hello guys . Just in case someone is having this issue.
@abdelibbi @thidasapankaja 
I found a solution to this. this worked :
`  <script src="cordova.js"></script>`
I forgot to add that. Add it to the first file that loads, which is often index.html .
We often miss the simple things :)
