### ISSUE TITLE
Package name not in sync with Ionic

### ISSUE THREAD

**Issue by aggarwalankush** [Rohfosho/CordovaCallNumberPlugin#26]
Please see this issue if you can fix it https://github.com/driftyco/ionic-native/issues/643#issuecomment-251839647

**Comment by telran** [comment]
please release your package in NPM with the name "mx.ferreyra.callnumber".

**Comment by masimplo** [comment]
With Cordova 7 trying to restore packages found in config.xml and not package.json (can't find it since names do not match) this turned into a real headache. Please address this issue.
