### ISSUE TITLE
Auto Dial on android

### ISSUE THREAD

**Issue by Ross-Rawlins** [Rohfosho/CordovaCallNumberPlugin#30]
Does this plugin bypass the user having to still dial the number on android?

**Comment by kashban** [comment]
That's something I need to know too. 

Clearly the App has to request additional permission from the user to be able to achieve this.

**Comment by ColDrekken** [comment]
hi, need to know too.

**Comment by Ross-Rawlins** [comment]
it does auto dial and works like a charm
