### ISSUE TITLE
Error:CouldNotCallPhoneNumber

### ISSUE THREAD

**Issue by Onyekam** [Rohfosho/CordovaCallNumberPlugin#31]
Hi,
When trying to dial USSD codes with this plugin on ios device (works well on android devices) I get this error:

> Error:CouldNotCallPhoneNumber

What could be the reason?

**Comment by kmikzjh** [comment]
I have same issue, but with emergency numbers like 911 (in my country are 133, 131, etc...), and works well on android :/
