### ISSUE TITLE
Error when I'm trying to add plugin

### ISSUE THREAD

**Issue by Jenq** [rohfosho/CordovaCallNumberPlugin#43]
running 'cordova plugin add https://github.com/Rohfosho/CordovaCallNumberPlugin.git' in console and get this:

Error: Failed to fetch plugin https://github.com/Rohfosho/CordovaCallNumberPlugin.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

Whit connection all is ok, checked. Cordova version: 7.0.1

**Comment by smiklakhani** [comment]
Hey @Jenq, I noticed the same thing when I was trying to install it but it ended up not actually being related to the connection. You may have the plugin already installed, and may need to uninstall it first.

In my case, I had initially successfully installed the plugin through "cordova plugin add ...", but was trying to install it again using "**ionic** cordova plugin add ...", which is when I got the error. I then ran "cordova plugin remove ..." and after that the "ionic cordova plugin add ..." command worked fine. Hope this helps.

**Comment by theHellyar** [comment]
this fixed my issues of always wanting to install the 'mx.ferreyra.callnumber'

just remove all plugins 'mx.ferreyra.callnumber' and 'call-number'

then past this in your config file:
`<plugin name="call-number" spec="1.0.4" />`

then run `ionic cordova prepare` and it will install the latest version and the console will never try to install 'mx.ferreyra.callnumber ' again.... happy days!
