### ISSUE TITLE
"Success"-Function will never be called on iOS

### ISSUE THREAD

**Issue by bennybennet** [Rohfosho/CordovaCallNumberPlugin#5]
As you're never doing 
```
pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK]; 
```
in CFCallNumber.m the Error-Function will always be the called one (under iOS at least).

**Comment by lakano** [comment]
This explain why this doesn't callback under iOS... 
@Rohfosho : Could you please update your plugin ? :-)
Regards

**Comment by nishilshah17** [comment]
I believe I have fixed it.
