### ISSUE TITLE
Not able to install the latest version 

### ISSUE THREAD

**Issue by jvaranam** [Rohfosho/CordovaCallNumberPlugin#51]
While installing the plugin, getting the following error

      ` ionic cordova plugin add call-number
         > cordova plugin add call-number --save
         ✖ Running command - failed!
         [ERROR] An error occurred while running cordova plugin add call-number --save (exit code 
         Error: Failed to fetch plugin git+https://github.com/Rohfosho/CordovaCallNumberPlugin.git via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Failed to get absolute path to installed module`

Even the same error while i use the github path too.

**Comment by mohamedsharaf** [comment]
DONT USE CORDOVA PLUGIN ADD

USE THIS FIXED IT FOR ME

npm install call-number
