### ISSUE TITLE
Can't call since your last update

### ISSUE THREAD

**Issue by lakano** [Rohfosho/CordovaCallNumberPlugin#7]
Hello, 

I recreated my ionic application few minutes ago, and I can't call anymore. 
I receive an "CouldNotCallPhoneNumber" Error each time ( +33123456789 ) 

I see you have just made some changes in code one hour ago, it's may be a new bug ?

Regards

**Comment by nishilshah17** [comment]
Hello, please try it now. Made the update.

**Comment by dansanti** [comment]
Hi ! if i remove last change :

intent.setData(Uri.parse(Uri.encode(number))); 

to 

intent.setData(Uri.parse(number));


Now i can make calls, why do you use Uri.encode?

**Comment by nishilshah17** [comment]
You are right. Fixed.
