### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by Galiza** [rohfosho/CordovaCallNumberPlugin#71]
I just can't make it work, I followed everything that the repo says and still nothing.

Here's my code:

HTML
`<button ion-button full round padding (click)="call()">Ligar</button>`

TypeScript
`  public call(): void {
    this.callNumber.callNumber("123456789", true);
  }`

> RealtyPage.html:69 ERROR TypeError: Object(...) is not a function
>     at CallNumber.callNumber (vendor.js:78072)
>     at RealtyPage.webpackJsonp.211.RealtyPage.call (main.js:232)
>     at Object.eval [as handleEvent] (RealtyPage.html:69)
>     at handleEvent (vendor.js:13921)
>     at callWithDebugContext (vendor.js:15430)
>     at Object.debugHandleEvent [as handleEvent] (vendor.js:15017)
>     at dispatchEvent (vendor.js:10336)
>     at vendor.js:10961
>     at HTMLButtonElement.<anonymous> (vendor.js:39885)
>     at t.invokeTask (polyfills.js:3)

As soon as I click the button, this error appears.

**Comment by JavierConde** [comment]
Hi, i have the same issue.
You need to use a previous version.

https://ionicframework.com/docs/v3/native/call-number/

This works for me.

**Comment by Galiza** [comment]
> Hi, i have the same issue.
> You need to use a previous version.
> 
> https://ionicframework.com/docs/v3/native/call-number/
> 
> This works for me.

Thank you so much. As soon as I changed the version, it instantly worked!
