### ISSUE TITLE
Call plugin to Windows Phone and Blackberry

### ISSUE THREAD

**Issue by mubasshir** [Rohfosho/CordovaCallNumberPlugin#8]
Hi,
Its nice, to the point plugin and very well written. I just want to know if you can extend to Windows Phone and Blackberry so that it completes the smart phone cycle.

**Comment by Rohfosho** [comment]
Hey, I don't have much time on my hands to port to Windows Phone or Blackberry. You're free to port and make a pull request and I'll happily merge!
